import { Router } from 'express';
import authRoutes from './auth.routes';
import lessonRoutes from './lessons.routes';
import exerciseRoutes from './exercises.routes';
import progressRoutes from './progress.routes';
import chapterRoutes from './chapters.routes';
import adminRoutes from './admin.routes';
import dashboardRoutes from './dashboard.routes';
import writingRoutes from './writing.routes';
import userRoutes from './user.routes';
import widgetsRoutes from './widgets.routes';
import flashcardRoutes from './flashcards.routes';
import paymentRoutes from './payment.routes';
import contentRoutes from './content.routes';
import announcementRoutes from './announcement.routes';
import settingsRoutes from './settings.routes';
import speakingRoutes from './speaking.routes';

const router = Router();
router.get('/health', (_req, res) => {
  res.status(200).json({ success: true, message: 'FrancPrep API is running', timestamp: new Date().toISOString() });
});
router.use('/auth', authRoutes);
router.use('/lessons', lessonRoutes);
router.use('/chapters', chapterRoutes);
router.use('/exercises', exerciseRoutes);
router.use('/progress', progressRoutes);
router.use('/admin', adminRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/writing', writingRoutes);
router.use('/user', userRoutes);
router.use('/widgets', widgetsRoutes);
router.use('/flashcards', flashcardRoutes);
router.use('/payments', paymentRoutes);
router.use('/content', contentRoutes);
router.use('/announcements', announcementRoutes);
router.use('/settings', settingsRoutes);
router.use('/speaking', speakingRoutes);
export default router;
