import { AUTHENTIC_READING_MASTER_BANK } from "../src/lib/authenticReadingMasterBank";
import * as fs from "fs";

const replacements: Record<string, string> = {
  // Paper 1 Q30
  "1-30": `CRITICAL ESSAY — ECONOMIC SOCIOLOGY REVIEW: PARADOXES OF THE SECOND-HAND MARKET AND VIRTUOUS CONSUMPTION.\n\nThe spectacular emergence of digital platforms dedicated to second-hand trading is widely celebrated by contemporary commercial discourse as the triumphant symbol of eco-responsible and restrained consumption. Yet a thorough sociological analysis of purchasing behaviors reveals insidious side effects that contradict this soothing rhetoric. A fierce stimulus for the frantic renewal of wardrobes and household equipment, facilitated reselling actually feeds an underlying dynamic of hyper-consumption.\n\nIndeed, the constant possibility of quickly liquidating prior purchases relieves buyer guilt, convincing consumers that their impulsive acquisitions remain ecologically neutral. Moreover, this market fluidity completely obscures the global carbon footprint generated by individualized packaging, logistics processing, and international road or air transport of millions of pre-owned parcels. Thus, under the guise of ethics and circular economy, the second-hand market faithfully reproduces the accumulation logic of consumer society.`,

  // Paper 1 Q31
  "1-31": `LINGUISTICS AND DIVERSIFICATION — FRANCOPHONIE PAPERS: PLURICENTRISM AND VITALITY OF THE FRENCH LANGUAGE WORLDWIDE.\n\nUnderstanding the global Francophone space through the exclusive prism of a centralized, unified linguistic norm constitutes a major conceptual anachronism in the 21st century. The true contemporary dynamic of French lies precisely in the pluricentrism of its regional expressions and the rich neological creativity originating from the Americas, Africa, and Europe. This diversity of usage bears witness to a living appropriation of the language by varied cultural communities that daily shape its evolution.\n\nFar from eroding the integrity of the French language, these lexical and syntactic variations enrich the shared linguistic heritage without impairing international mutual intelligibility. By agreeing to frame French within a plurality of legitimate and equivalent norms, Francophone institutions consolidate its status as a living international language adaptable to contemporary world transformations.`,

  // Paper 1 Q32
  "1-32": `MEDIA AND SCIENCE — SCIENTIFIC RESEARCH REVIEW: DRIFTS OF SENSATIONALIST MEDIA POPULARIZATION.\n\nScientific outreach work intended for the general public requires an extremely delicate balance between readability of expression and maintaining conceptual rigor. However, yielding to the demands of media sensationalism and the frantic quest for immediate ratings, certain news channels resort to an excessive simplification of scientific discourse. In this pursuit of artificial clarity, they eliminate all methodological nuance and specialized vocabulary.\n\nThis reductive distortion profoundly alters public perception of empirical research. By presenting preliminary speculations as immutable scientific certainties, these media drifts foster a deplorable distrust toward methodical doubt. Yet this capacity for constant questioning constitutes the very essence of the scientific spirit and the engine of knowledge progress.`,

  // Paper 1 Q33
  "1-33": `URBAN PLANNING AND ARCHITECTURE — CONTEMPORARY URBANISM PAPERS: RECONVERSION OF INDUSTRIAL BROWNFIELDS INTO VIBRANT CULTURAL SPACES IN METROPOLITAN AREAS.\n\nReconverting disused industrial brownfields into cultural centers and contemporary creation spaces represents a particularly bold, ambitious, and innovative urban development strategy. By choosing to scrupulously preserve original brick facades and steel frameworks while inserting sleek architectural volumes, designers achieve a harmonious synthesis between working-class memory of the sites and modern functionality.\n\nFar from yielding to a museum nostalgia that freezes the past in marble in a sterile manner, these rehabilitations deeply revitalize the social and economic fabric of once-marginalized neighborhoods. They brilliantly demonstrate that intelligent preservation of industrial heritage can become the catalyst for sustainable, inclusive urban regeneration creating permanent, non-relocatable local jobs.`,

  // Paper 1 Q35
  "1-35": `LITERARY CRITICISM — NOVEL AESTHETICS REVIEW: HERMENEUTICS AND THE NARRATOR FIGURE IN THE CONTEMPORARY MODERNIST NOVEL.\n\nThe emergence of the unreliable narrator figure in contemporary novelistic creation forces the reader to break permanently with the comforting posture of a passive receiver. Confronted with a decentered narrative marked by deliberate omissions, temporal distortions, and contradictory perspectives, the reader is invited to conduct a genuine critical investigation across pages to reconstruct the sequence of actual events.\n\nBy refusing to dictate a single truth or ready-made moral, the modernist author transforms the act of reading into a demanding and stimulating hermeneutic quest. In this innovative framework, the ultimate meaning of the work is no longer a pre-existing given to be passively consumed, but a dynamic construction requiring the active involvement, methodical interpretation, and creative imagination of the reader within the textual universe itself.`,

  // Paper 1 Q36
  "1-36": `PHILOSOPHICAL ESSAY — TRIBUNE IN THE ANNALS OF CONTEMPORARY PHILOSOPHY: COMMODIFICATION OF TIME AND EROSION OF COLLECTIVE MEMORY IN MODERN SOCIETIES.\n\nThe systematic commodification of temporality within our post-industrial societies has gradually altered the ability of human communities to anchor themselves in cumulative historical memory. Subject to the demands of digital immediacy and constant economic yield, lived time becomes fragmented into a succession of fleeting sequences, stripped of their original symbolic depth. Modern individuals consume the present moment without managing to articulate it into a meaningful duration.\n\nThis disarticulation of historical duration transforms foundational events of collective memory into simple consumable and quickly disposable news products. By obscuring the organic continuity between past and future in favor of a perpetually agitated present, the commercial model deprives human experience of its hermeneutic grounding. This temporal amnesia weakens the transmission of civic consciousness and suffocates any capacity for long-term political projection.`,

  // Paper 1 Q39
  "1-39": `PHILOSOPHICAL ANTHROPOLOGY — HUMANIST STUDIES REVIEW: SYMBOLISM AS THE FUNDAMENTAL HUMAN CONDITION.\n\nThe specific human capacity to secrete meaning through complex symbolic forms cannot be reduced to a superfluous cultural luxury or a secondary aesthetic entertainment. On the contrary, it constitutes the very ontological framework of our presence in the world, through which humans manage to structure reality and ward off fundamental existential dread of nothingness. Without this symbolic mediation, human existence would lapse into chaos and meaninglessness.\n\nIt is through the medium of language, myth, and ritual that the individual breaks away from biological immediacy to construct a universe of ethical intersubjectivity and shared values. Obscuring this symbolic dimension in favor of a reductive materialism amounts to stripping humanity of the narrative framework that grounds its dignity and moral responsibility.`,

  // Paper 2 Q30
  "2-30": `POLITICAL ECONOMY — TRIBUNE IN THE CONTEMPORARY MACROECONOMICS REVIEW: SELECTIVE DEGROWTH IN QUESTION AND MAINTAINING SOCIAL PROGRESS.\n\nPromoting selective degrowth as a single miracle solution to global ecological crises without prior modeling of its impact on social protection systems represents a theoretical posture disconnected from economic and social realities. Lacking a prior structural revision of taxation and value-added redistribution methods, any deliberate, unregulated slowdown of productive activity would strike vulnerable populations first.\n\nWithout a reinforced health and financial safety net, declining activity would risk destroying low-skilled jobs en masse and severely eroding public revenues dedicated to funding health and pensions. Thus, without prior redistributive regulation, a legitimate ecological aspiration would inevitably tilt into a devastating social crisis for low-income groups.`,

  // Paper 2 Q31
  "2-31": `SOCIOLINGUISTICS AND CULTURES — CULTURAL DIVERSITY PAPERS: ECOLOGY OF ENDANGERED LANGUAGES AND COGNITIVE DIVERSITY AT RISK.\n\nThe accelerated disappearance of minority tongues constitutes not merely a tragic linguistic heritage loss, but represents an irreparable erosion of the cognitive diversity of all humanity. Because every language structures a unique cosmogony, a singular worldview, and an original classification of living species, the death of a linguistic system equals the definitive destruction of a true library of ecological and philosophical knowledge accumulated over centuries of presence in the world.\n\nBy neglecting active preservation of endangered languages, modern societies deliberately deprive themselves of irreplaceable conceptual tools developed by local cultures to interact in harmony with their ecosystems. This linguistic impoverishment reduces humanity's overall capacity to conceptualize innovative solutions facing complex contemporary ecological challenges.`,

  // Paper 2 Q34
  "2-34": `FUNDAMENTAL RIGHTS AND TECHNOLOGY — DIGITAL LAW AND FREEDOMS REVIEW: FACIAL RECOGNITION AND PUBLIC SPACE IN CONTEMPORARY ETHICAL AND LEGAL DEBATE.\n\nThe accelerated deployment of automated facial recognition technologies in public spaces establishes continuous panoptic surveillance that alters the very nature of fundamental democratic freedoms. Confronted with the permanent risk of biometric identification during daily commutes across the city, citizens manifest self-censorship behaviors that severely alter freedom of assembly and peaceful demonstration in shared urban spaces.\n\nFacing this uncontrolled security drift, numerous legal scholars and civil liberties advocates argue for establishing a strict moratorium prohibiting mass biometric surveillance. This legal protection is indispensable for preserving the anonymity necessary for unconstrained exercise of democratic, participatory civic life in an open, pluralistic, and free society.`,

  // Paper 2 Q35
  "2-35": `LITERARY THEORY AND POETICS — CONTEMPORARY POETICS REVIEW: FRAGMENTARY FORM IN 20TH-CENTURY MODERNIST ESSAYS AND READER EMANCIPATION.\n\nBy repudiating the explanatory continuity and linearity of classical philosophical treatises in favor of fragmentary forms, 20th-century essayists convey the dislocation of the modern subject. Fragments must by no means be interpreted as incomplete thought or narrative logic failure, but as a deliberate rejection of closed dogmatic systems and externally imposed authoritarian synthesis.\n\nBy offering readers open meditative cells freed from peremptory conclusions, fragment poetics require active intellectual participation. In this innovative framework, every discontinuity becomes a privileged space for reflective re-reading and autonomous co-creation of textual meaning by an empowered, sovereign reader engaged in reading.`,

  // Paper 2 Q36
  "2-36": `SOCIO-PHILOSOPHICAL CRITIQUE — TRIBUNE IN THE METAPHYSICAL CRITICISM PAPERS: THE ILLUSION OF HISTORICAL ACCELERATION AND STRUCTURAL STASIS OF LATE CAPITALISM IN QUESTION.\n\nContemporary rhetoric saturated with themes of exponential time acceleration and technical progress masks in reality a deep structural stasis. Beneath the veneer of permanent technological turmoil and frantic commercial gadget turnover, the fundamental structures of late capitalism and political institutions remain singularly frozen and incapable of genuine innovation. Constant innovation confines itself to remodeling product surfaces without altering system logic.\n\nThis underlying immobility deprives our era of the capacity to generate a true metaphysical or social alternative. Reduced to a superficial and repetitive hyperactivity, contemporary society simulates perpetual motion to perpetuate a frozen order incapable of conceiving its own historical and political transformation.`,

  // Paper 2 Q37
  "2-37": `PHILOSOPHY OF NATURE — CONTEMPORARY EPISTEMOLOGY ANNALS: REIFICATION OF THE LIVING AND DISENCHANTMENT OF THE MATERIAL WORLD IN CONTEMPORARY TECHNO-SCIENCE.\n\nThe subjugation of nature by modernist techno-science has transformed the world from a cosmos inhabited by mystery into a simple reservoir of energy and resources exploitable at will. This methodical disenchantment deprives humanity of its original ecosystemic grounding, reducing Earth relations to a unilateral relationship of utilitarian and accounting domination. Every living natural element is thus reified and converted into a monetizable commodity on global markets.\n\nBy erasing the sacrality of the living in favor of a narrow accounting materialism, modernity broke the symbolic dialogue between humans and their surrounding environment. Restoring an ethical presence requires breaking radically with this exploitation logic to rebuild an ecology of interdependency respectful of life in all its forms.`,

  // Paper 2 Q38
  "2-38": `CULTURAL CRITICISM — AVANT-GARDE AESTHETICS REVIEW: KITSCH GENEALOGY AND DESTRUCTURING IN CONTEMPORARY GLOBAL MASS MEDIA.\n\nKitsch is not characterized by a simple absence of individual taste or a lack of artistic education, but constitutes a structured aesthetics of easy sentiment and immediate emotional comfort. By eliminating all dialectical tension and tragic conflict in favor of a counterfeit harmony, contemporary kitsch acts as a powerful cultural narcotic ensuring global ideological pacification of masses. The demanding complexity of authentic art is thus swept away.\n\nBy offering pre-formatted and immediately consumable emotions, kitsch industries neutralize critical thought by satisfying individual desires for certainty and comforting illusions. Authentic art thus opposes kitsch radically by maintaining the wound of reality and the complexity of metaphysical doubt facing human existence.`,

  // Paper 2 Q39
  "2-39": `ETHICS AND ALTERITY — ANNALS OF MORAL PHILOSOPHY: IRREDUCIBLE ALTERITY AS ETHICAL FOUNDATION OF CONTEMPORARY HUMANITY AND THE FACE OF THE OTHER QUESTIONED IN MODERN SOCIETIES.\n\nTrue ethics by no means derives from a contract of self-interested reciprocity signed between rational individuals seeking the maximization of personal gain, but originates in unconditional and asymmetrical responsibility toward the face of the other. It is in the trial of irreducible alterity, which traumatically ruptures the solipsism of the Self, that the very possibility of justice and moral duty takes root. Man becomes fully human only by truly answering for the other.\n\nBy placing the other at the center of ultimate philosophical concern, this ethical anthropology breaks radically with modern narcissism. Recognizing oneself as vulnerable before the call of the other forms the sole authentic bulwark against the barbarism of individual selfishness and disastrous identitarian withdrawal.`,

  // Paper 3 Q30
  "3-30": `SOCIETAL CRITIQUE — POLITICAL SOCIOLOGY TRIBUNE: ILLUSIONS OF DIGITAL PARTICIPATORY DEMOCRACY.\n\nInstitutionalizing online citizen consultation platforms by public authorities is frequently framed as the advent of direct, transparent, and inclusive democracy. By enabling every resident to submit proposals or vote on urban development projects, official rhetoric claims to erase the distance between governing bodies and citizens. However, attentive observation of participant demographics reveals a glaring representative distortion. Digital consultation initiatives heavily overrepresent upper socio-professional categories endowed with high cultural capital, deepening the exclusion of working classes from public debate.\n\nFurthermore, the purely advisory nature of these systems leaves decision-making bodies discretionary power to select or dismiss citizen proposals without binding justification. Far from renewing civic deliberation, digital democracy risks devolving into a simple PR exercise validating choices made upstream by administrative elites. Consequently, substituting algorithmic illusions of clicking for real political debate threatens to worsen the crisis of trust toward representative institutions.`,

  // Paper 9 Q35
  "9-35": `ARCHITECTURE AND CITY — CONTEMPORARY URBAN PLANNING REVIEW: FACADE STANDARDIZATION AND REGIONAL UNGROUNDING IN MODERN MONDIALIZED METROPOLISES.\n\nThe widespread adoption of standardized industrial materials (metal cladding, mirror glass facades, precast concrete) in contemporary construction produces a generic, repetitive, and interchangeable urban landscape. From Tokyo business districts to European city entrances, repeating identical neutral architectural forms erases the material identity and secular history of territories.\n\nThis loss of regional identity deeply degrades residents' sense of belonging to their home neighborhood. Stripped of stylistic continuity with local heritage and indifferent to regional climate demands, globalized architecture reduces cities to cold functional assemblies that stifle human sensitivity and the daily poetic experience of living environments. Re-enchanting urban planning demands imperatively re-enforcing the use of local bio-sourced materials.`
};

function fixTruncatedTranslations() {
  console.log("=== 🛠️ APPLYING EXHAUSTIVE ACADEMIC TRANSLATIONS TO FLAGGED ITEMS ===");

  const fullBank = [...AUTHENTIC_READING_MASTER_BANK];

  let appliedCount = 0;

  Object.entries(replacements).forEach(([key, newPassEn]) => {
    const [pStr, qStr] = key.split("-");
    const paperNum = parseInt(pStr, 10);
    const qNum = parseInt(qStr, 10);

    const paperIndex = paperNum - 1;
    const qIndex = qNum - 1;

    if (fullBank[paperIndex] && fullBank[paperIndex][qIndex]) {
      fullBank[paperIndex][qIndex].passEn = newPassEn;
      appliedCount++;
      console.log(`✅ Applied updated passEn to Paper ${paperNum} Q${qNum} (${fullBank[paperIndex][qIndex].level})`);
    }
  });

  const content = `import type { ReadingItem } from "./examSchema";

export interface ReadingItem {
  paperNum: number;
  qNum: number;
  level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  docType: string;
  text: string;
  q: string;
  opt: [string, string, string, string];
  ans: number;
  passEn: string;
  qEn: string;
  optEn: [string, string, string, string];
}

// Master Reading Question Bank for 10 Papers x 39 Questions = 390 Calibrated Authentic Reading Questions.
export const AUTHENTIC_READING_MASTER_BANK: ReadingItem[][] = ${JSON.stringify(fullBank, null, 2)};

export function getReadingPaperItems(paperId: number): ReadingItem[] {
  const index = (paperId - 1) % AUTHENTIC_READING_MASTER_BANK.length;
  return AUTHENTIC_READING_MASTER_BANK[index] || AUTHENTIC_READING_MASTER_BANK[0];
}
`;

  fs.writeFileSync("src/lib/authenticReadingMasterBank.ts", content);
  console.log(`\n🎉 Successfully applied ${appliedCount} exhaustive academic translations to src/lib/authenticReadingMasterBank.ts!`);
}

fixTruncatedTranslations();
